# I want to use babel-eslint for parsing!
parser: babel-eslint

parserOptions:
    ecmaVersion: 2018

settings:
    react:
        createClass: createReactClass
        pragma: React
        version: detect
        flowVersion: "0.53"

env:
    # I write for browser
    browser: true,
    # in CommonJS
    node: true
    es6: true

plugins:
    - react

extends:
    - eslint:recommended
    - plugin:react/recommended

# To give you an idea how to override rule options:
rules:
    quotes: 0
    key-spacing: 0
    comma-spacing: 0
    no-trailing-spaces: 0
    no-underscore-dangle: 0
    react/jsx-no-undef: 2
    react/jsx-no-duplicate-props: 2
    react/no-deprecated: 0
    react/display-name: 0
    react/prop-types: [2, { ignore: ["children"] }]
    strict: 0
    no-loop-func: 2
    eqeqeq: [2, "allow-null"]
    no-console: 0
    no-unused-expressions: 2
    no-unused-vars: 1
    no-use-before-define: 2
    no-with: 2
    consistent-return: 2
    curly: 2
    new-cap: 2
    semi: 2
    space-infix-ops: 2
    indent: ["error", 4]
